### ISSUE TITLE
你好，您这个项目在swift 5上面运行，导航栏部分会空出来，如果有时间您可以看一下

### ISSUE THREAD

**Issue by Xcode123456** [smlkts/MDNavigationBar_swift#1]
![image](https://user-images.githubusercontent.com/28332571/70968936-8afa3e00-20d5-11ea-9640-fa8e5d3a6b5f.png)

**Comment by smlkts** [comment]
在scrollview上添加      
  if #available(iOS 11.0, *) {
            tableView.contentInsetAdjustmentBehavior = .never
        } else {
            // Fallback on earlier versions
        }
不过随着ios系统版本升级 现在这个控件应该会有很多问题了 不建议使用了

**Comment by Xcode123456** [comment]
好的，感谢您的回答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yanj"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 晚上6:03
收件人:&nbsp;"smlkts/UINavigationBar-Fade-Swift"<UINavigationBar-Fade-Swift@noreply.github.com&gt;;
抄送:&nbsp;"522053506"<522053506@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [smlkts/UINavigationBar-Fade-Swift] 你好，您这个项目在swift 5上面运行，导航栏部分会空出来，如果有时间您可以看一下 (#1)




在scrollview上添加
 if #available(iOS 11.0, *) {
 tableView.contentInsetAdjustmentBehavior = .never
 } else {
 // Fallback on earlier versions
 }
 不过随着ios系统版本升级 现在这个控件应该会有很多问题了 不建议使用了
